### PR TITLE
Adding some padding to the right of the simple snippet icon.

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
@glogiotatidis r?

This is the fix for the small pixel issue we found yesterday.

I decided on increasing the existing margin instead of adding a new padding. Seemed simpler to me.

**Comment by glogiotatidis** [comment]
@schalkneethling can you please check this one? Discussion in https://github.com/mozmar/snippets/pull/83#issuecomment-243472038

**Comment by schalkneethling** [comment]
looks good to me r+

**Comment by glogiotatidis** [comment]
Thanks both!

**Comment by glogiotatidis** [comment]
Oh wrong commit message :|

**Pull request merged**
