### PR TITLE
[bug 1342029] Move block button more to the top and right.

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Hey @ScottDowne could you please r?

**Comment by ScottDowne** [comment]
Looking :)

**Comment by ScottDowne** [comment]
Definitely an improvement R+. I think after this fix, most of the other potential improvements are around the snippet overlay highlight. I just played with a few other places for the x, but ultimately I ended up to around where you put it :)

For the overlay experience, I always liked how it's done here https://people-mozilla.org/~shorlander/about-home-snippet-opt-out/about-home-test-01.html

I would be willing to write any code to do this. That is, if you think we have a clear path towards that, from a branding/design pov?

**Comment by glogiotatidis** [comment]
> For the overlay experience, I always liked how it's done here https://people-mozilla.org/~shorlander/about-home-snippet-opt-out/about-home-test-01.html
> 
> I would be willing to write any code to do this. That is, if you think we have a clear path towards that, from a branding/design pov?

I like it too! I'll merge any PRs that fix this but I'd check with :shorlander and Jean to verify that this is still wanted

**Comment by glogiotatidis** [comment]
> Definitely an improvement R+. I think after this fix, most of the other potential improvements are around the snippet overlay highlight. I just played with a few other places for the x, but ultimately I ended up to around where you put it :)

Thanks!

**Pull request merged**
