### PR TITLE
Horizontal padding for longer translations

### PR DESCRIPTION
**Pull request by TheoChevalier**
Fixing https://github.com/MozillaFoundation/Advocacy/issues/643 for the upcoming Italian translation (and potentially other languages)

### CODE REVIEW

**Comment by ScottDowne** [comment]
I'm thinking we also add a `max-width: 132px;` to ensure it never moves the button to the next line:

Example, this vs this:

good
bad

It should still fit the it locale translation in one line, this is just to protect us a bit from the unexpected, maybe?

**Comment by TheoChevalier** [comment]
That’s definitely a good idea :)

**Comment by ScottDowne** [comment]
Just pinging @glogiotatidis here, (who's pretty busy right now) as the person that can review this. This should be a pretty simple patch, though :)

**Comment by glogiotatidis** [comment]
Thanks both!

**Pull request merged**
